# Generated by Django 3.2.23 on 2024-02-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240110_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
